version: '3.8'

services:
  # Serviço do Frontend (Nginx)
  frontend:
    image: nginx:latest
    container_name: autou-frontend
    ports:
      - "8080:80"   # Expõe a porta 8080 da máquina local para a porta 80 do Nginx
    volumes:
      - ./app/frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always

  # Serviço do Backend (Python com FastAPI)
  backend:
    container_name: autou-backend
    build:
      context: .
      dockerfile: app/backend/Dockerfile  # Caminho correto para o Dockerfile
    env_file:
      - ./app/backend/.env   # Carregar variáveis de ambiente do arquivo .env
    ports:
      - "5001:5001"   # Mapeia a porta 5001 da máquina local para a porta 5001 do contêiner
    restart: always
